usua *insertarEnUsua(usua *apuntador);
void mostrarListaUsua(usua *apuntador);
void crearArchivos(FILE * ptd, FILE *ptk);
void saveInFile_dataUsua(usua *apuntador, usua *apuntador2, FILE *ptd);
curs *insertarEnMaterias(curs *apuntador, usua *apuntador2);
void mostrarListaMateria(curs *apuntador);
void saveInFile_dataMateria(curs *apuntador, FILE *ptd);
int buscarDatoCrearCuenta(usua *apuntador, char *cedula);
int ingresarCuenta(usua *apuntador, char *apodo, char *clave);
void buscarUsername(usua *apuntador, curs *apuntador2, char *apodo);
void mostrarCursos(curs *apuntador, char *nombre);
nota *definirNotas(nota *apuntador);
curs *buscaMateria(curs *apuntador, int num);
curs *ingresarNotas(usua *apuntador2, int num, curs *apuntador3);
int buscarCedula(char *cedula, usua *apuntador);
void mostrarListaStudiantAProfesor(usua *apuntador);
curs *buscaMateria2(curs *apuntador, int num);
int numeroNotas(nota *apuntador);
void informacionDeMateriaAStudieant(usua *apuntador, curs *apuntador2,  char *apodo);
